

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo-database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: go_backend_neww
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  frontend:
    build:
      context: .
    container_name: react_frontend_neww
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
